services:
  cases:
    image: amitesh81/parties:v1
    container_name: partis-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - efileCasesNetwork